title: "cat-obsidian-templater-scripts"
description: "cat-obsidian-templater-scripts"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/cat-obsidian-templater-scripts
